version: "3.9"

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: the-lost-of-us-db
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: the_lost_of_us

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: